version: "3.8"

services:
    postgres:
        extends:
            file: docker-compose.yml
            service: postgres
        networks:
            - database

    migrate:
        extends:
            file: docker-compose.yml
            service: migrate

    whosbest:
        image: cosmtrek/air:latest
        working_dir: /whosbest
        expose:
            - 3000
        entrypoint: ["air", "-c", ".air.toml"]
        deploy:
            replicas: 1
        networks:
            - database
            - loadbalancer
        volumes:
            - ./:/whosbest
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - JWT_SECRET=${JWT_SECRET}

    nginx:
        extends:
            file: docker-compose.yml
            service: nginx
        networks:
            - loadbalancer

volumes:
    data:

networks:
    database:
        driver: bridge
    loadbalancer:
        driver: bridge
